// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcbb2lU5UoQk2atw9JFk-rW3Cy_f6RwDo',
    appId: '1:331269996580:web:5c89da298b660ed6e3d8b1',
    messagingSenderId: '331269996580',
    projectId: 'doctolib-dc50e',
    authDomain: 'doctolib-dc50e.firebaseapp.com',
    storageBucket: 'doctolib-dc50e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_soTT5Y60hKTOSNmzuzHmGRogUQgfUF0',
    appId: '1:331269996580:android:efb808ab781b6fb7e3d8b1',
    messagingSenderId: '331269996580',
    projectId: 'doctolib-dc50e',
    storageBucket: 'doctolib-dc50e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9HgcEEKKYV-8gBT1Rt11u2qa6uoEMZJo',
    appId: '1:331269996580:ios:33c5dcbbf5514779e3d8b1',
    messagingSenderId: '331269996580',
    projectId: 'doctolib-dc50e',
    storageBucket: 'doctolib-dc50e.appspot.com',
    iosClientId: '331269996580-qj8kcnae38lh7p3g6pj9ubvhlc7ouhuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientdoctolib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9HgcEEKKYV-8gBT1Rt11u2qa6uoEMZJo',
    appId: '1:331269996580:ios:834a95ade5a3be12e3d8b1',
    messagingSenderId: '331269996580',
    projectId: 'doctolib-dc50e',
    storageBucket: 'doctolib-dc50e.appspot.com',
    iosClientId: '331269996580-u2img23m7squnugrr3is6lg68ftb2o7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientdoctolib.RunnerTests',
  );
}
